[package]
name = "ded-lock"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.tokio]
git = "https://github.com/tokio-rs/tokio"
rev = "d07c89ebd352bfe771f5594bff6cb87476120a6b"
default-features = false
features = ["rt-threaded"]
